// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwopsiduetlwehpcrkzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13b3BzaWR1ZXRsd2VocGNya3pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDczMzQsImV4cCI6MjA2NTUyMzMzNH0.LEW0Yv954JLgghQqwf51FZsRx7bkNFkl3a_2JzLEeZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);